name: elred
description: A task manager app created for elRed for screening.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  dartz: ^0.10.1
  cloud_firestore: ^3.4.1
  google_sign_in: ^5.4.0
  json_annotation: ^4.6.0
  flutter_screenutil: ^5.5.3+2
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.0
  provider: ^6.0.3
  lottie: ^1.4.1
  top_snackbar_flutter: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.7
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1


  build_runner: ^2.2.0
flutter:
  assets: 
    - assets/fonts/
    - assets/images/
    - assets/json/
  uses-material-design: true
